### ISSUE TITLE
Error in logs, shows not being marked unmonitored

### ISSUE THREAD

**Issue by gdtms247** [Ozymandyaz/sonarr-episode-trimmer#2]
I replaced all my files and rebuilt my config.ini, script is running and deleting files however the episodes are not marked as unmonitored and when I looked in logs I see an error. Trimmer and Sonarr log files attached and screen shot of the activity for example. 

About
Version: 4.0.1.929
Package Version: 4.0.1.929-ls224 by [linuxserver.io](https://linuxserver.io/)
.NET: Yes (6.0.13)
Docker: Yes
Database: Sqlite 3.44.2

[sonarr.txt](https://github.com/Ozymandyaz/sonarr-episode-trimmer/files/14223899/sonarr.txt)
[sonarr-episode-trimmer.log](https://github.com/Ozymandyaz/sonarr-episode-trimmer/files/14223719/sonarr-episode-trimmer.log)
![Screenshot 2024-02-09 at 9 50 12 AM](https://github.com/Ozymandyaz/sonarr-episode-trimmer/assets/31072325/dadea488-bdf3-4b12-8c38-fc437038cb03)

**Comment by Ozymandyaz** [comment]
Should be fixed by https://github.com/Ozymandyaz/sonarr-episode-trimmer/commit/379a0034d0c65dce294cdfd47b69a1462524d3a2

**Comment by gdtms247** [comment]
I replaced my sonarr-episode-trimmer.py file however issue remains still, log attached. 

[sonarr-episode-trimmer.log](https://github.com/Ozymandyaz/sonarr-episode-trimmer/files/14271414/sonarr-episode-trimmer.log)

**Comment by Ozymandyaz** [comment]
Try this - But be aware, you will need to install `Python3-Requests` so if your using docker you my need to update the init scripts, i.e. `python3-Alpine.sh` or `python3-Ubuntu.sh`

**Comment by gdtms247** [comment]
I am using docker and adding python in my compose, will test your suggestions, thanks!

**Comment by gdtms247** [comment]
That was it, the docker mod I had been using was python3 but it was not installing requests, got that added and script runs properly! thanks very much for maintaining this script for this function!!
